meta:
  site_title: "state.js"
  site_subtitle: "well-behaved JavaScript"
  site_language: "en"
  author:
    full_name: Nick Fargo
    short_name: nickfargo
    email: nick.fargo@gmail.com
    github: nickfargo
    twitter: nickfargo
  license: MIT
  license_url: http://github.com/nickfargo/state/blob/master/LICENSE

tag_dir: tag
pygments: true
baseurl: /state
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
exclude: [ art, diagrams ]

packages:
  state:
    version: 0.2.0
    size: 104kB
    size_gz: 16.5kB
