// Generated by CoffeeScript 1.6.3
(function() {
  var StateContent, state;

  state = require('./state-function');

  module.exports = StateContent = (function() {
    var useDispatchTables;

    useDispatchTables = state.options.useDispatchTables;

    function StateContent() {
      this.data = null;
      this.methods = null;
      this.events = null;
      this.guards = null;
      this.substates = null;
      this.transitions = null;
      if (useDispatchTables) {
        this.__dispatch_table__ = null;
      }
    }

    return StateContent;

  })();

}).call(this);
